INSERT OR IGNORE INTO question (id, type, text, is_default) VALUES
  (1, 'INTRO', 'Let''s start the interview now. Tell me a little bit about yourself.', 1),
  (2, 'INTRO', 'Tell me about your job or school. What do you do on a typical day?', 1),
  (3, 'INTRO', 'Tell me about your family and the people you live with.', 1),
  (4, 'INTRO', 'What do you usually do in your free time? Tell me about your hobbies.', 1),
  (5, 'INTRO', 'What kind of person are you? Describe your personality.', 1),
  (6, 'DESCRIBE', 'Describe your home. What does it look like, and how many rooms does it have?', 1),
  (7, 'DESCRIBE', 'Tell me about your neighborhood. What is it like, and what can you find there?', 1),
  (8, 'DESCRIBE', 'Describe a park you like to go to. Where is it, and what does it look like?', 1),
  (9, 'DESCRIBE', 'Describe your favorite cafe. What does it look like, and why do you like it?', 1),
  (10, 'DESCRIBE', 'Describe a place in your country that you like to visit on vacation.', 1),
  (11, 'ROUTINE', 'What do you usually do when you go to the movies? Tell me about it from beginning to end.', 1),
  (12, 'ROUTINE', 'What do you do on a typical weekend? Describe it in detail.', 1),
  (13, 'ROUTINE', 'Tell me about your morning routine on weekdays.', 1),
  (14, 'ROUTINE', 'How do you usually prepare for a trip? What do you do before you leave?', 1),
  (15, 'ROUTINE', 'What do you usually do when you go shopping? Walk me through a typical shopping trip.', 1),
  (16, 'PAST', 'Tell me about the most memorable trip you have taken. Where did you go, and what happened?', 1),
  (17, 'PAST', 'Tell me about a movie you saw recently. Who did you go with, and how was it?', 1),
  (18, 'PAST', 'Tell me about a problem you had at home and how you solved it.', 1),
  (19, 'PAST', 'Tell me about a memorable experience you had at a park.', 1),
  (20, 'PAST', 'Tell me about a time when something unexpected happened while you were traveling.', 1),
  (21, 'COMPARE', 'How has your neighborhood changed since you first moved there? Compare the past and the present.', 1),
  (22, 'COMPARE', 'Compare the movies you liked when you were young with the movies you like now.', 1),
  (23, 'COMPARE', 'How has the way people shop changed over the years?', 1),
  (24, 'COMPARE', 'Compare your home now with the home you lived in as a child.', 1),
  (25, 'COMPARE', 'How has technology changed the way people communicate?', 1),
  (26, 'ROLEPLAY', 'I''d like to give you a situation and ask you to act it out. You want to see a movie with a friend. Call your friend and ask three or four questions to make plans.', 1),
  (27, 'ROLEPLAY', 'I''d like to give you a situation and ask you to act it out. You are planning a trip. Call a travel agency and ask three or four questions about the trip.', 1),
  (28, 'ROLEPLAY', 'I''d like to give you a situation and ask you to act it out. You want to join a gym. Call the gym and ask three or four questions.', 1),
  (29, 'ROLEPLAY', 'I''m sorry, but there is a problem I need you to resolve. You bought a concert ticket, but you cannot go. Call your friend, explain the situation, and suggest two or three alternatives.', 1),
  (30, 'ROLEPLAY', 'I''m sorry, but there is a problem I need you to resolve. The item you ordered online arrived broken. Call the store, explain the problem, and suggest a solution.', 1),
  (31, 'UNEXPECTED', 'Tell me about the bank you usually go to. What does it look like, and what do you do there?', 1),
  (32, 'UNEXPECTED', 'Tell me about a hotel you have stayed at. What was it like?', 1),
  (33, 'UNEXPECTED', 'How do people in your country recycle? Describe the process.', 1),
  (34, 'UNEXPECTED', 'Describe the weather in your country. How is it different in each season?', 1),
  (35, 'UNEXPECTED', 'Tell me about a holiday people in your country celebrate. What do people do?', 1);
